name: dinney_restaurant
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  sizer: any
  flutter_riverpod: any
  go_router: any
  supabase_flutter: any
  image_picker: any
  uuid: any
  hugeicons: ^0.0.9
  intl: any
  google_maps_flutter: any
  location: any
  iconsax: any
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  # flutter_local_notifications: ^17.2.0
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  #google_maps_flutter: any
  # iconsax: any
  # image_picker: any
  # flutter_image_compress: any
  # permission_handler: any
  # location: any
  # connectivity: any
  # flutter_background_service: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # hive_generator: ^2.0.1
  # build_runner: ^2.4.7


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
